DROP TABLE IF EXISTS RECORDS;
DROP TABLE IF EXISTS USER_API_LIMIT_TRACKER;
DROP TABLE IF EXISTS USER_API_LIMIT_MASTER_DATA;

CREATE TABLE RECORDS (
  	ID VARCHAR2(250) NOT NULL UNIQUE,
  	USER_NAME VARCHAR2(250) NOT NULL,
  	CITY VARCHAR2(250),
  	AGE NUMERIC(10,0)
);

CREATE TABLE USER_API_LIMIT_TRACKER (
 	ID VARCHAR2(250) NOT NULL UNIQUE,
  	USER_ID VARCHAR2(250) NOT NULL ,
  	API_NAME VARCHAR2(250) NOT NULL,
  	CURRENT_SECOND_RATE NUMERIC(10,0),
 	CURRENT_SECOND  NUMERIC(10,0)
);

CREATE TABLE USER_API_LIMIT_MASTER_DATA (
 	ID VARCHAR2(250) NOT NULL UNIQUE,
  	USER_ID VARCHAR2(250) NOT NULL ,
  	API_NAME VARCHAR2(250) NOT NULL,
  	USER_API_RATE_LIMIT NUMERIC(10,0)
);


INSERT INTO USER_API_LIMIT_MASTER_DATA VALUES('1234567','client-id', 'GET /records', 20);